on: workflow_dispatch
jobs:
  greet:
    runs-on: ubuntu-latest # only linux container available
    steps:
      - name: Success
        run: echo "First Job successful"
  job-2:
    runs-on: ubuntu-latest
    needs: greet # specify dependecy
    steps:
      - name: Success
        run: echo "Run after first job"
  job-3:
    runs-on: ubuntu-latest
    needs: [greet,job-3]
    steps:
      - name: Success
        run: echo "Run after second job"