on: 
  repository_dispatch:
    types: [my_input]
jobs:
  greet:
    runs-on: ubuntu-latest # only linux container available
    steps:
      - name: Greet the user
        env:
          NAME: ${{github.event.client_payload.name}}
        run: echo "Hello $NAME"