on: workflow_dispatch
jobs:
  greet:
    runs-on: ubuntu-latest # only linux container available
    steps:
      - name: Check out the Repo
        uses: actions/checkout@v4 # default checkout ${{ github.repository }}
      - name: Greet the user
        run: echo "Hello World"