on: 
  workflow_dispatch:
    inputs: # define inputs
      name: # input#1 is called name
        required: True # required input
        type: string # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputsinput_idtype
        default: "World"
      run_it: 
        required: False
        type: boolean
        default: True
jobs:
  greet:
    # check if we can run_it is True
    if: ${{inputs.run_it}} # can be job-level or step-level
    runs-on: ubuntu-latest
    env:
      NAME: ${{inputs.name}} # Pass the GitHub env variable into the container
    steps:
      - name: Greet the user
        run: echo "Hello $NAME"
        