name: jacks-workflow

on: push

jobs:
  job1:
    # use another workflow
    # cannot specify version in a local workflow
    uses: ./.github/workflows/build-test.yml
    with:
      node-version: '18.x'
    # test skip ci