name: Trigger greet.yml
on: workflow_dispatch
jobs:
	job1:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: |
        gh api \
        --method POST \
        -H "Accept: application/vnd.github+json" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        /repos/trinuro/actions-learning-pathway/dispatches \
          -f "event_type=my_input" -F "client_payload[name]=Superman"
    env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}