name: Create new release

on:
  pull_request:
    types: [labeled] # Trigger every PR with labels

jobs:
  job1:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release 
        if: contains(github.event.pull_request.labels.*.name, 'release')
        uses: actions/create-release@v1 # not maintained
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: v${{github.run_number}}
      