name: test-custom-action
on: workflow_dispatch
jobs:
  test-action:
    name: test action 
    runs-on: ubuntu-latest
    steps:
      - uses: trinuro/learn-custom-actions@v1.2
        id: greet
        with:
          who-to-greet: froginacup
      - run: echo "Action ran on ${{steps.greet.output.time}}" 
        # To access the output of a step, give it an id and assess it using steps.<id>.output.time