name: MySQL container example
on: workflow_dispatch
jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      mysql: # label/hostname of the system
        image: mysql
        ports: 3306:3306 # default mysql port
    steps:
      - name: Check running ports
        run: ss -tlnp
