name: "Workflow Commands"
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name : "Group logging"
        run: |
          echo "::group::Group Message example"
          echo "Msg 1"
          echo "Msg 2"
          echo "::endgroup::"
      - name: "Debug Message"
        run: echo "::debug::This is a debug Message"
      - name: Mask value
        run: echo "::add-mask::${{secrets.GITHUB_TOKEN}}"
      - name: Trigger failure
        run: echo "::error::This is an error message"