name: upload-file-artifact
on: workflow_dispatch
jobs:
  create-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Create file 
        run: echo "Hi, I am $GITHUB_ACTOR in $GITHUB_REPOSITORY. I am in $GITHUB_PATH" > hello.txt
      - name: Upload artifact 
        uses: actions/upload-artifact@v4
        with:
          path: hello.txt
          name: user_info
      - name: Download current workflow artifact
        uses: actions/download-artifact@v4
        with:
          name: user_info
          path: hello_current.txt
      - name: Download previous workflow artifact
        uses: actions/download-artifact@v4
        with:
          name: user_info
          run-id: ${{github.run_id}} - 1
          path: hello_old.txt
      - name: List the current dir 
        run: ls 
